def print_menu():
    print("\n==== Student Management System ====")
    print("1. Add New Student")
    print("2. Add New Course")
    print("3. Enroll Student in Course")
    print("4. Add Grade for Student")
    print("5. Display Student Details")
    print("6. Display Course Details")
    print("7. Save Data to File")
    print("8. Load Data from File")
    print("0. Exit")
